name: flame_wall_breaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  flame_audio: ^2.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/  
